ShareUrThoughts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'ShareUrThoughts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('accounts.urls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),
)

posts/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView

from posts.views import (PostsList, CreatePost, UpdatePost,
                         DeletePost, post_detail, create_comments)



urlpatterns = patterns('',
    # url(r'^(?P<username>\w+)/$', TemplateView.as_view(template_name='posts/user_posts.html'), name='user_posts'),
    # url(r'^(?P<username>\w+)/$', user_posts, name='user_posts'),

    # username Matches alphanumeric and spl char(-._+@)

    url(r'^(?P<username>[\w.@+-]+)/$', PostsList.as_view(), name='user_posts'),
    url(r'^(?P<username>\w+)/create$', CreatePost.as_view(), name='create_post'),
    url(r'^(?P<username>\w+)/update/(?P<slug>[-\w]+)$', UpdatePost.as_view(), name='update_post'),
    url(r'^(?P<username>\w+)/delete/(?P<slug>[-\w]+)$', DeletePost.as_view(), name='delete_post'),
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', post_detail, name='post_detail'),

    #comment
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/comment$', create_comments, name='create_comment'),
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/reply/(?P<p_id>[0-9]+)$', create_comments, name='create_reply'),


)

posts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from mptt.models import MPTTModel, TreeForeignKey


class Post(models.Model):
    fk_user = models.ForeignKey(User)
    title = models.CharField(max_length=255, null=False, blank=False)
    text = models.TextField()
    posted_on = models.DateField(default=datetime.now)
    deleted = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.id, 'slug': self.slug})

    def get_update_url(self):
        return reverse('posts:update_post', kwargs={'username': self.fk_user.username, 'slug': self.slug})

    def get_delete_url(self):
        return reverse('posts:delete_post', kwargs={'username': self.fk_user.username, 'slug': self.slug})


class Comment(MPTTModel):
    fk_user = models.ForeignKey(User)
    fk_post = models.ForeignKey(Post)
    comment = models.TextField(max_length=255)
    parent_cmt = TreeForeignKey('self', null=True, blank=True, related_name='child_cmt', db_index=True)
    commented_on = models.DateField(default=datetime.now)
    deleted = models.BooleanField(default=False)

    class MPTTMeta:
        parent_attr = 'parent_cmt'
        order_insertion_by = ['commented_on']

    def __unicode__(self):
        return '%s - comment' % self.fk_user

posts/forms.py
import ipdb
import itertools
from django.template.defaultfilters import slugify

from posts.models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'text']

    def save(self):
        instance = super(PostForm, self).save(commit=False)

        orig = slugify(instance.title)
        instance.slug = orig

        # truncate the slug to 50 char
        if len(orig) > 50:
            instance.slug = orig[:48]+'--'

        for x in itertools.count(1):
            if not Post.objects.filter(slug=instance.slug).exists():
                break
            instance.slug = '%s-%d' % (orig, x)

        instance.save()

        return instance


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment']
        widgets = {
            'comment': forms.Textarea(attrs={'rows': 1,'cols': 50}),
        }

posts/views.py
import ipdb

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (ListView, CreateView, UpdateView,
                                  DeleteView)
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404

from accounts.views import LoginRequiredMixin
from posts.models import Post, Comment
from posts.forms import PostForm, CommentForm

# Create your views here.


# views for posts
class PostsList(LoginRequiredMixin, ListView):
    template_name = 'posts/user_posts.html'

    def get_queryset(self):
        # ipdb.set_trace()
        user_obj = User.objects.get(username=self.kwargs['username'])
        qs = Post.objects.filter(fk_user__username=user_obj.username, deleted=False)
        return qs

    def get_context_data(self, **kwargs):
        context = super(PostsList, self).get_context_data(**kwargs)
        context['user'] = User.objects.get(username=self.kwargs['username'])
        return context


class CreatePost(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = 'posts/create_and_update.html'

    def form_valid(self, form):
        # ipdb.set_trace()

        form.instance.fk_user = User.objects.get(username=self.kwargs['username'])
        return super(CreatePost, self).form_valid(form)

    def get_success_url(self):
        return reverse('posts:user_posts', kwargs={'username': self.kwargs['username']})


def post_detail(request, pk, slug):
    # ipdb.set_trace()
    post = get_object_or_404(Post, slug=slug)
    node_set = post.comment_set.all()

    return render(request, 'posts/post_detail.html', {'post': post, 'node_set': node_set})


class UpdatePost(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'posts/create_and_update.html'

    def get_object(self):
        # ipdb.set_trace()
        user_obj = User.objects.get(username=self.kwargs['username'])
        obj = Post.objects.get(fk_user__username=user_obj.username, deleted=False, slug=self.kwargs['slug'])
        return obj


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_post.html'

    def get_success_url(self):
        return '/posts/%s' % self.kwargs['username']

    def get_object(self):
        # ipdb.set_trace()
        user_obj = User.objects.get(username=self.kwargs['username'])
        obj = Post.objects.get(fk_user__username=user_obj.username, deleted=False, slug=self.kwargs['slug'])
        return obj

    def delete(self, request, *args, **kwargs):
        # ipdb.set_trace()
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.deleted = True
        self.object.save()

        return HttpResponseRedirect(success_url)


# views for comments

@login_required
def create_comments(request, **kwargs):
    # ipdb.set_trace()
    post = get_object_or_404(Post, slug=kwargs['slug'])
    node_set = post.comment_set.all()

    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            user_obj = request.user
            form.instance.fk_user = user_obj
            try:
                post_obj = Post.objects.get(slug=kwargs['slug'])
                form.instance.fk_post = post_obj

                # if reply
                if kwargs.has_key('p_id'):
                    form.instance.parent_cmt = Comment.objects.get(id=kwargs['p_id'])

                form.save()
                form.save()
                node_set = post_obj.comment_set.all()
            except ObjectDoesNotExist:
                raise Http404

            return render(request, 'posts/post_detail.html', {'post': post_obj, 'node_set': node_set,})

        else:
            form = CommentForm()
            if kwargs.has_key('p_id'):
                form.instance.parent_cmt = Comment.objects.get(id=kwargs['p_id'])
                form_type = 'reply_'
            else:
                form_type = 'comment_'

    else:
        form = CommentForm()
        if kwargs.has_key('p_id'):
            form.instance.parent_cmt = Comment.objects.get(id=kwargs['p_id'])
            form_type = 'reply_'
        else:
            form_type = 'comment_'

    return render(request, 'posts/comment_form.html', {'form': form, 'post': post, 'node_set': node_set,
                                                       'form_type': form_type})

posts/templates/posts/comment_form.html
{% extends "posts/post_detail.html" %}

{% block extrahead %}
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script>
        $(document).ready(function (){
            $("html, body").animate({ scrollTop: $(document).height() }, 1000);
            window.onload = function() {
                $("#id_comment").focus();
                // focus to a textbox
                }
        });
    </script>
{% endblock %}


{% block cmt_and_replay_form %}
    <div>
        {% if user.is_anonymous %}
            <a class="pure-button" href="{% url 'signin' %}?next={{ request.path }}">You must sign in to comment</a> &nbsp;

        {% else %}
            <form  class="pure-form pure-form-aligned" method="post">
                <div class="pure-control-group">
                    {% csrf_token %}
                    <div class="pure-control-group">
                    
                    {% for field in form.visible_fields %}
                        {{ field }}                      
                    {% endfor %}
                    <button type="submit" value="{{ next }}" id="scrollD_form" class="pure-button pure-button-primary">
                        {% if form_type == "reply_" %}                        
                            reply
                        {% else %}
                            comment
                        {% endif %}
                    </button>

                    </div>
                </div>
            </form>
        </div>
        {% endif %}
{% endblock cmt_and_replay_form %}

posts/templates/posts/create_and_update.html
{% extends "base.html" %}

{% block content %}
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <form  class="pure-form pure-form-aligned" method="post">
                <div class="pure-control-group">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <div class="pure-controls">
                    <button type="submit" value="{{ next }}" class="pure-button pure-button-primary">Share</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/create_post.html
{% extends "base.html" %}

{% block content %}
    <form  method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input value="Share" type="submit">
    </form>
{% endblock %}

posts/templates/posts/delete_post.html
{% extends "base.html" %}

{% block content %}
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            <form  class="pure-form pure-form-aligned" method="post">
                <div class="pure-control-group">
                    {% csrf_token %}
                    <p>Are you sure you want to delete "{{ object }}"?</p>
                </div>
                <div class="pure-controls">
                    <button type="submit" value="Confirm" class="pure-button pure-button-primary">Delete</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% load mptt_tags %}



{% block content %}
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
        <!-- A wrapper for all the blog posts -->
            <div class="posts">
                <section class="post">
                    <header class="post-header">
                            <h2 class="post-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h2>
                            <p class="post-meta">
                                By {{ post.fk_user.first_name }} on {{ post.posted_on }}
                            </p>
                    </header>
                    <div class="post-description">
                        <p>
                            {{ post.text|linebreaks }}
                        </p>
                        <ul style="list-style: none;">
                            <p class="post-meta">
                                {% if user.is_anonymous %}
                                    <a href="{% url 'signin' %}?next={{ request.path }}">add comment</a> &nbsp;
                                {% else %}
                                    <a href="{% url 'posts:create_comment' pk=post.id slug=post.slug %}">add comment</a>
                                {% endif %}
                            </p>
                            {% recursetree node_set %}
                                <li>
                                    <hr style="border-color:#FFFFFF; width:100%; ">
                                    <div class="post-description">
                                        {{ node.comment }}
                                    </div>
                                    <p class="post-meta">
                                        by {{ node.fk_user.first_name }} on {{ node.commented_on }}
                                    </p>

                                        {% if user.is_anonymous %}
                                            <p class="post-meta"><a href="{% url 'signin' %}?next={{ request.path }}">Reply</a></p>
                                        {% else %}
                                            <p class="post-meta"><a href="{% url 'posts:create_reply' pk=post.id slug=post.slug p_id=node.id %}">Reply</a></p>
                                        {% endif %}

                                        {% if not node.is_leaf_node %}
                                            <ul class="children" style="list-style: none;" >
                                                {{ children }}
                                            </ul>
                                    {% endif %}

                                </li>
                            {% endrecursetree %}
                        </ul>

                        {% block cmt_and_replay_form %}

                        {% endblock cmt_and_replay_form %}

                    </div>
                </section>
            </div>
        </div>
    </div>
{% endblock content %}

posts/templates/posts/user_posts.html
{% extends "base.html" %}




{% block content %}
    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
        <!-- A wrapper for all the blog posts -->
            <div class="posts">
                <h1 class="post-header">
                    <a href="{% url 'posts:create_post' user.username %}">Share new thoughts
                    </a>
                </h1>
                <hr style="border-color:#FFFFFF; width:100%; ">
                <section class="post">
                {% for post in object_list %}
                    <header class="post-header">
                            <h2 class="post-title">
                                <a href="{{ post.get_update_url }}">{{ post.title }}</a>
                            </h2>
                            <p class="post-meta">
                                posted on {{ post.posted_on }}
                                <a class="pure-button" href="{{ post.get_delete_url }}">Delete </a>
                            </p>
                    </header>
                    <div class="post-description">
                        <p>
                            {{ post.text|linebreaks }}
                        </p>
                    </div>
                {% empty %}
                    <p class="post-meta">
                    No thoughts ...
                    </p>
                {% endfor %}

                </section>
            </div>
        </div>
    </div>
{% endblock content %}